gems: ['jekyll/scholar']
exclude: ['package.json', 'Gruntfile.js', 'Rakefile', 'Gemfile', 'Gemfile.lock']

title:            Ash Tyndall
logo:             square200.jpg
disqus_shortname: atyndall
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://ash.id.au

# Owner/author information
owner:
  name:           Ash Tyndall
  email:          hi@ash.id.au
  # Social networking links used in footer. Update and remove as you like.
  twitter: atyndall            
  github: atyndall         
  linkedin: ashtyndall/           
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/+AshTyndall

# Analytics and webmaster tools stuff goes here
google_analytics: UA-29830465-2      

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Perth
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /post/:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


scholar:
  style: ./assets/ieee-mod.csl
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
